env:
  es6: true
  browser: true
extends: 
 - "eslint:recommended"
 - "plugin:react/recommended"
plugins:
  - "babel"
parserOptions:
  sourceType: module
  ecmaFeatures: 
    experimentalObjectRestSpread: true  
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
