sudo: required
dist: trusty
language: node_js

matrix:
  include:
    - os: osx
    - os: linux
      services: docker
      language: generic

node_js:
  - "8"

install:
  - yarn

script:
  - yarn dist
   

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine