sudo: required
dist: trusty
language: node_js

matrix:
  include:
    - os: osx
    - os: linux
      services: docker
      language: generic

node_js:
  - "8"

install:
  - yarn

script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker run --rm \
        --env-file <(env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|_TOKEN|_KEY|AWS_|STRIP|BUILD_') \
        -v ${PWD}:/project \
        -v ~/.cache/electron:/root/.cache/electron \
        -v ~/.cache/electron-builder:/root/.cache/electron-builder \
        electronuserland/builder:wine \
        /bin/bash -c "rm -r node_modules && yarn && yarn remove node-sass && yarn add node-sass && yarn dist --linux --win"
    else
      yarn dist
    fi

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine